### ISSUE TITLE
 I can't install 2.60

### ISSUE THREAD

**Issue by pafurijaz** [gcad3d/gcad3d#49]
Hi I can't install the latest version of gCAD3D, in Linux xubuntu 22.04 LTS, the software installer after installation crashes and shows the installed application but nothing works, I tried with gdebi but with that it even crashes crash as soon as I press the install button.

I don't know what the problem could be but in fact I can't launch the application, I wanted to install the previous version which at least works, but now I can't find even an old build, how install a previous version? 
greetings.

**Comment by gcad3d** [comment]
Hallo; the problem is the missing of gtkglarea-2 for Ubu22 and all new RPM-
packages.
We use at the moment the package
https://builds.garudalinux.org/repos/chaotic-aur/x86_64/gtkglarea-2.1.0-6.3-x86_64.pkg.tar.zst
- it helps for Ubu22 and all new RPM-packages.
If you want to use a binary package, we can provide it now;
if you prefer the github-package,
please wait - the iges export is beeing rewritten completely.
Greetings.

**Comment by gcad3d** [comment]
Found a much better solution:
sudo apt install libgtkgl2.0-1

**Comment by pafurijaz** [comment]
I was here answering, now I'm fine but I will wait for the next build with IGES export that I use to export DXF in to a CAD. Thanks

Greetings

**Comment by pafurijaz** [comment]
Now works thanks feel free to close this issue-

**Comment by gcad3d** [comment]
New binary version with bugfixes and libgtkgl2.0-1 (for Ubuntu 22) is online; 
The only libgtkgl2 - package for rpm we found is
https://builds.garudalinux.org/repos/chaotic-aur/x86_64/gtkglarea-2.1.0-6.3-x86_64.pkg.tar.zst
- works for Fedora 35 (installation manually).
